version: '3.9'
services:
  web:
    container_name: golang_container
    env_file:
     - .env
    tty: true
    build: .
    restart: on-failure
    volumes:
    - .:/app
    depends_on:
    - postgresdb
    networks:
    - smt_city

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    env_file:
     - .env
    ports:
      - '1234:5432'
    networks:
      - smt_city
    volumes:
      - postgresdb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresdb:

networks:
  smt_city:
    driver: bridge
