version: '3.9'
services:
  web:
    container_name: golang_container
    env_file:
      - .env
    tty: true
    build: .
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgresdb
    networks:
      - smt_city

  # export PGPASSWORD=Qwerty@123;psql -h postgresdb -U traffic_user -d traffic_db
  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
    ports:
      - '5432:5432'
    networks:
      - smt_city
    volumes:
      - postgresdb:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresdb:


networks:
  smt_city:
    driver: bridge
