@baseURL =  http://localhost:8000/api/v1

### Health API Check
GET http://localhost:8000/health

### Create Sensor Request
POST {{baseURL}}/sensor/
Content-Type: application/json

{
  "latitude": 30.712776,
  "longitude": -44.005974,
  "rate": 1.8,
  "status": true
}

### Fetch All Sensor Request
GET {{baseURL}}/sensor/

### Fetch All Sensor Request filters
GET {{baseURL}}/sensor/?status=true


### Fetch Sensor By Id Request
GET {{baseURL}}/sensor/4461bbb6-d067-4399-8eec-0f5f3e98cc2a

### Update Sensor By Id Request
GET {{baseURL}}/sensor/388b9eac-3816-4409-bfe9-5356fb5b3814
Content-Type: application/json

{
  "status": true
}

### Traffic data
POST {{baseURL}}/traffic/
Content-Type: application/json

{
  "sensor_id": "4461bbb6-d067-4399-8eec-0f5f3e98cc2a",
  "vericle_count": 5,
  "average_speed": 10.0
}

### Fetch Traffic data
GET {{baseURL}}/traffic/6
Content-Type: application/json
