@baseURL =  http://localhost:8000/api/v1

### Health API Check
GET http://localhost:8000/health

### Create Sensor Request
POST {{baseURL}}/sensor/
Content-Type: application/json

{
  "latitude": 40.712776,
  "longitude": -24.005974,
  "rate": 0.9,
  "status": true
}

### Fetch All Sensor Request
GET {{baseURL}}/sensor/?status=false

Content-Type: application/json
